#ifndef SPEAR_SPEAR_HH
#define SPEAR_SPEAR_HH

#include <spear/camera.hh>
#include <spear/create_scene.hh>
#include <spear/event_handler.hh>
#include <spear/game_object.hh>
#include <spear/material.hh>
#include <spear/mesh.hh>
#include <spear/model/obj_loader.hh>
#include <spear/movement_controller.hh>
#include <spear/physics/bullet/object.hh>
#include <spear/physics/bullet/object_data.hh>
#include <spear/physics/bullet/world.hh>
#include <spear/physics/constants.hh>
#include <spear/physics/physics_object.hh>
#include <spear/rendering/api.hh>
#include <spear/rendering/base_model.hh>
#include <spear/rendering/base_shader.hh>
#include <spear/rendering/base_texture.hh>
#include <spear/rendering/shader_type.hh>
#include <spear/rendering/shapes/shape.hh>
#include <spear/rendering/shapes/textured_shape.hh>
#include <spear/scene.hh>
#include <spear/scene_manager.hh>
#include <spear/spear_root.hh>
#include <spear/time.hh>
#include <spear/transform.hh>

// OpenGL
#include <spear/rendering/opengl/material.hh>
#include <spear/rendering/opengl/model/obj_model.hh>
#include <spear/rendering/opengl/renderer.hh>
#include <spear/rendering/opengl/shader.hh>
#include <spear/rendering/opengl/shapes/cube.hh>
#include <spear/rendering/opengl/shapes/quad.hh>
#include <spear/rendering/opengl/shapes/sphere.hh>
#include <spear/rendering/opengl/texture/sdl_texture.hh>
#include <spear/rendering/opengl/texture/stb_texture.hh>
#include <spear/rendering/opengl/texture/texture.hh>

// Vulkan
#include <spear/rendering/vulkan/core/command_buffer_manager.hh>
#include <spear/rendering/vulkan/core/device_manager.hh>
#include <spear/rendering/vulkan/core/framebuffer_manager.hh>
#include <spear/rendering/vulkan/core/pipeline_manager.hh>
#include <spear/rendering/vulkan/core/render_pass_manager.hh>
#include <spear/rendering/vulkan/core/swapchain.hh>
#include <spear/rendering/vulkan/core/synchronization.hh>
#include <spear/rendering/vulkan/frame_context.hh>
#include <spear/rendering/vulkan/mesh.hh>
#include <spear/rendering/vulkan/renderer.hh>
#include <spear/rendering/vulkan/shader.hh>
#include <spear/rendering/vulkan/shapes/cube.hh>
#include <spear/rendering/vulkan/shapes/textured_cube.hh>
#include <spear/rendering/vulkan/texture/stb_texture.hh>
#include <spear/rendering/vulkan/texture/texture.hh>

#endif
